# Use Node.js base image
FROM node:22-alpine AS build

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the frontend code
COPY . .

# Build the frontend
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html