# Generated by Django 5.2.6 on 2025-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_alter_glcodemaster_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycategoriesmaster',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='citycategoriesmaster',
            name='name',
            field=models.CharField(db_index=True, help_text='Short category code like A, B, C', max_length=10, null=True, unique=True),
        ),
    ]
