# Generated by Django 5.2.6 on 2025-12-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_citycategoriesmaster_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citycategoriesmaster',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='citycategoriesmaster',
            name='name',
            field=models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C')], max_length=1, unique=True),
        ),
    ]
