# Generated by Django 5.2.6 on 2025-12-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_remove_citycategoriesmaster_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citycategoriesmaster',
            name='name',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
