# Generated by Django 5.2.6 on 2025-12-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_alter_citycategoriesmaster_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grademaster',
            name='sorting_no',
            field=models.PositiveIntegerField(),
        ),
    ]
