# Generated by Django 5.2.6 on 2026-01-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_alter_grademaster_sorting_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glcodemaster',
            name='sorting_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
