# Generated by Django 5.2.6 on 2026-01-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_alter_glcodemaster_sorting_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='glcodemaster',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
