# Generated by Django 5.2.6 on 2026-01-17 06:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_glcodemaster_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletypemaster',
            options={'verbose_name': 'Vehicle Type Master', 'verbose_name_plural': 'Vehicle Type Master'},
        ),
        migrations.AddField(
            model_name='vehicletypemaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='vehicletypemaster',
            table='vehicle_type_master',
        ),
        migrations.CreateModel(
            name='VehicleCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle Category Master',
                'verbose_name_plural': 'Vehicle Category Master',
                'db_table': 'vehicle_category_master',
                'indexes': [models.Index(fields=['code'], name='vehicle_cat_code_c53f86_idx'), models.Index(fields=['is_active'], name='vehicle_cat_is_acti_b083a6_idx')],
            },
        ),
        migrations.AlterField(
            model_name='vehicletypemaster',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_types', to='master_data.vehiclecategorymaster'),
        ),
        migrations.AddIndex(
            model_name='vehicletypemaster',
            index=models.Index(fields=['name'], name='vehicle_typ_name_3a89f3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletypemaster',
            index=models.Index(fields=['category'], name='vehicle_typ_categor_7d4936_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletypemaster',
            index=models.Index(fields=['capacity'], name='vehicle_typ_capacit_30827f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletypemaster',
            index=models.Index(fields=['is_active'], name='vehicle_typ_is_acti_3104a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicletypemaster',
            constraint=models.UniqueConstraint(fields=('name', 'category', 'capacity'), name='uniq_vehicle_type_name_cat_cap_travel'),
        ),
    ]
