# Generated by Django 5.2.6 on 2026-01-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0023_alter_vehicletypemaster_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehiclecategorymaster',
            new_name='master_data_code_4b015c_idx',
            old_name='vehicle_cat_code_c53f86_idx',
        ),
        migrations.RenameIndex(
            model_name='vehiclecategorymaster',
            new_name='master_data_is_acti_67a5a0_idx',
            old_name='vehicle_cat_is_acti_b083a6_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicletypemaster',
            new_name='master_data_name_1c7fc7_idx',
            old_name='vehicle_typ_name_3a89f3_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicletypemaster',
            new_name='master_data_categor_67377e_idx',
            old_name='vehicle_typ_categor_7d4936_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicletypemaster',
            new_name='master_data_capacit_da0c8b_idx',
            old_name='vehicle_typ_capacit_30827f_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicletypemaster',
            new_name='master_data_is_acti_a525fd_idx',
            old_name='vehicle_typ_is_acti_3104a3_idx',
        ),
        migrations.AlterModelTable(
            name='vehiclecategorymaster',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vehicletypemaster',
            table=None,
        ),
    ]
