# Generated by Django 5.2.6 on 2026-01-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0024_rename_vehicle_cat_code_c53f86_idx_master_data_code_4b015c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmaster',
            name='dept_code',
            field=models.CharField(max_length=50),
        ),
    ]
