# Generated by Django 5.2.6 on 2026-01-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0025_alter_departmentmaster_dept_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designationmaster',
            name='designation_code',
            field=models.CharField(max_length=50),
        ),
    ]
