# Generated by Django 5.2.6 on 2026-01-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0026_alter_designationmaster_designation_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departmentmaster',
            name='unique_department_code_per_company',
        ),
    ]
