# Generated by Django 5.2.6 on 2026-01-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0027_remove_departmentmaster_unique_department_code_per_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designationmaster',
            name='designation_name',
            field=models.CharField(max_length=255),
        ),
    ]
