# Generated by Django 5.2.6 on 2026-01-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0028_alter_designationmaster_designation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archotelmaster',
            name='facilities',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='archotelmaster',
            name='room_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='archotelmaster',
            name='social_media',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
