# Generated by Django 5.2.6 on 2026-01-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0029_alter_archotelmaster_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archotelmaster',
            name='facilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='archotelmaster',
            name='room_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='archotelmaster',
            name='social_media',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
