# Generated by Django 5.2.6 on 2026-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0030_alter_archotelmaster_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archotelmaster',
            name='category',
            field=models.CharField(blank=True, choices=[('3_star', '3 Star'), ('4_star', '4 Star'), ('5_star', '5 Star'), ('budget', 'Budget'), ('deluxe', 'Deluxe')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='archotelmaster',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archotelmaster',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archotelmaster',
            name='rate_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
