# Generated by Django 5.2.6 on 2026-01-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0031_alter_archotelmaster_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPreferenceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('allowed_modes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
