# Generated by Django 5.2.6 on 2026-02-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0032_mealpreferencemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmaster',
            name='location_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
