# Generated by Django 5.2.12 on 2026-06-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0033_alter_locationmaster_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelmodemaster',
            name='is_self_arranged',
            field=models.BooleanField(default=False, help_text='Default self-arranged for this travel mode'),
        ),
        migrations.AddField(
            model_name='travelsuboptionmaster',
            name='is_self_arranged',
            field=models.BooleanField(default=False, help_text='Default self-arranged for this sub-option'),
        ),
    ]
