# Generated by Django 5.2.6 on 2026-01-22 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_claimstatusmaster_expensetypemaster_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClaimFinanceActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('previous_status_code', models.CharField(blank=True, max_length=50)),
                ('new_status_code', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('action_date', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_action_logs', to='expenses.expenseclaim')),
            ],
            options={
                'ordering': ['-action_date'],
            },
        ),
    ]
