# Generated by Django 5.2.6 on 2026-01-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expenseclaim_closed_on_expenseclaim_paid_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='is_booking_expense',
            field=models.BooleanField(default=False),
        ),
    ]
