# Generated by Django 5.2.6 on 2026-01-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expenseitem_is_booking_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
