# Generated by Django 5.2.6 on 2026-02-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expenseitem_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='actual_travel_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='actual_travel_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='actual_travel_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='actual_travel_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
