# Generated by Django 5.2.12 on 2026-06-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expenseclaim_actual_travel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='one_way_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-way distance in kilometers entered by the user during claim submission', max_digits=8, null=True),
        ),
    ]
