# Generated by Django 5.2.6 on 2026-06-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expenseclaim_one_way_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='claim_remark',
            field=models.TextField(blank=True, help_text='User remarks entered during claim application submission', null=True),
        ),
    ]
