# Generated by Django 5.2.6 on 2025-12-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_organizationalprofile_organizatio_employe_104b31_idx_and_more'),
        ('master_data', '0016_alter_glcodemaster_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalprofile',
            name='service_cities',
            field=models.ManyToManyField(blank=True, help_text='Cities this booking agent serves', related_name='booking_agents', to='master_data.citymaster'),
        ),
    ]
