# Generated by Django 5.2.6 on 2025-12-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_externalprofile_service_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalprofile',
            name='serves_all_cities',
            field=models.BooleanField(default=False, help_text='If enabled, agent serves all cities'),
        ),
    ]
