# Generated by Django 5.2.6 on 2025-12-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_externalprofile_serves_all_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalprofile',
            name='employee_code',
            field=models.CharField(blank=True, help_text='Alpha Emp Code from HRMS', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hrms_id',
            field=models.IntegerField(blank=True, help_text='Physical ID from HRMS system', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, help_text='Mobile number from HRMS', max_length=15, null=True),
        ),
    ]
