# Generated by Django 5.2.6 on 2026-01-17 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_organizationalprofile_employee_code_user_hrms_id_and_more'),
        ('master_data', '0023_alter_vehicletypemaster_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalProfile',
            new_name='BookingAgentProfile',
        ),
        migrations.AlterModelTable(
            name='bookingagentprofile',
            table='external_profiles',
        ),
        migrations.AlterModelOptions(
            name='bookingagentprofile',
            options={'verbose_name': 'Booking Agent Profile', 'verbose_name_plural': 'Booking Agent Profiles'},
        ),
    ]
