# Generated by Django 5.2.6 on 2026-01-17 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_bookingagentprofile_delete_externalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingagentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='booking_agent_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
