# Generated by Django 5.2.6 on 2026-01-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_bookingagentprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingagentprofile',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='bookingagentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookingagentprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='bookingagentprofile',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='bookingagentprofile',
            name='serves_all_cities',
        ),
        migrations.RemoveField(
            model_name='bookingagentprofile',
            name='service_categories',
        ),
        migrations.RemoveField(
            model_name='bookingagentprofile',
            name='service_cities',
        ),
        migrations.AddIndex(
            model_name='bookingagentprofile',
            index=models.Index(fields=['organization_name'], name='booking_age_organiz_b8785e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagentprofile',
            index=models.Index(fields=['is_active'], name='booking_age_is_acti_173fea_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagentprofile',
            index=models.Index(fields=['is_verified'], name='booking_age_is_veri_3b028c_idx'),
        ),
        migrations.AlterModelTable(
            name='bookingagentprofile',
            table='booking_agent_profiles',
        ),
    ]
