# Generated by Django 5.2.6 on 2026-01-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_bookingagentprofile_contact_person_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookingagentprofile',
            new_name='authenticat_organiz_c611c3_idx',
            old_name='booking_age_organiz_b8785e_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingagentprofile',
            new_name='authenticat_is_acti_b8544b_idx',
            old_name='booking_age_is_acti_173fea_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingagentprofile',
            new_name='authenticat_is_veri_7ce29b_idx',
            old_name='booking_age_is_veri_3b028c_idx',
        ),
        migrations.AlterModelTable(
            name='bookingagentprofile',
            table=None,
        ),
    ]
