# Generated by Django 5.2.6 on 2026-02-16 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_rename_booking_age_organiz_b8785e_idx_authenticat_organiz_c611c3_idx_and_more'),
        ('master_data', '0033_alter_locationmaster_location_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSPOCAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spoc_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('locations', models.ManyToManyField(blank=True, related_name='spoc_assignments', to='master_data.locationmaster')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spoc_assignments', to='authentication.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spoc_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location SPOC Assignment',
                'verbose_name_plural': 'Location SPOC Assignments',
                'indexes': [models.Index(fields=['role', 'is_active'], name='authenticat_role_id_3452e9_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
