# Generated by Django 5.2.6 on 2026-05-05 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryApproverAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text="Reason for temporary authorization (e.g., 'Promotion to B-3 effective next month')")),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, help_text='Admin/CHRO who granted this authorization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_temp_authorizations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User being granted temporary approval authority', on_delete=django.db.models.deletion.CASCADE, related_name='temp_approver_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporary Approver Authorization',
                'verbose_name_plural': 'Temporary Approver Authorizations',
                'indexes': [models.Index(fields=['user', 'is_active'], name='authenticat_user_id_7d1527_idx'), models.Index(fields=['valid_from', 'valid_until'], name='authenticat_valid_f_6dc36d_idx')],
            },
        ),
    ]
