# Generated by Django 5.2.6 on 2026-01-20 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0017_remove_bookingagentprofile_contact_person_and_more'),
        ('master_data', '0028_alter_designationmaster_designation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profile Type Master',
                'verbose_name_plural': 'Profile Type Master',
                'db_table': 'profile_type_master',
                'indexes': [models.Index(fields=['code'], name='profile_typ_code_77df14_idx'), models.Index(fields=['is_active'], name='profile_typ_is_acti_57d25f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingAgentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serves_all_cities', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='authentication.bookingagentprofile')),
                ('service_cities', models.ManyToManyField(blank=True, help_text='Cities this service supports (if serves_all_cities is False)', related_name='booking_agent_services', to='master_data.citymaster')),
                ('profile_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_agent_services', to='booking_agent.profiletypemaster')),
            ],
            options={
                'verbose_name': 'Booking Agent Service',
                'verbose_name_plural': 'Booking Agent Services',
                'db_table': 'booking_agent_services',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('booking_group', models.CharField(choices=[('ticket', 'Ticket'), ('accommodation', 'Accommodation'), ('conveyance', 'Conveyance'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Category Master',
                'verbose_name_plural': 'Service Category Master',
                'db_table': 'service_category_master',
                'indexes': [models.Index(fields=['code'], name='service_cat_code_7e26e5_idx'), models.Index(fields=['booking_group'], name='service_cat_booking_848546_idx'), models.Index(fields=['is_active'], name='service_cat_is_acti_98723c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileTypeServiceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to='booking_agent.profiletypemaster')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_mappings', to='booking_agent.servicecategorymaster')),
            ],
            options={
                'verbose_name': 'Profile Type Service Map',
                'verbose_name_plural': 'Profile Type Service Maps',
                'db_table': 'profile_type_service_map',
            },
        ),
        migrations.CreateModel(
            name='BookingAgentServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_agent_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='booking_agent.bookingagentservice')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_agent_service_links', to='booking_agent.servicecategorymaster')),
            ],
            options={
                'verbose_name': 'Booking Agent Service Category',
                'verbose_name_plural': 'Booking Agent Service Categories',
                'db_table': 'booking_agent_service_categories',
            },
        ),
        migrations.CreateModel(
            name='BookingAgentAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_rules', to='master_data.citymaster')),
                ('booking_agent_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='booking_agent.bookingagentservice')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules', to='booking_agent.servicecategorymaster')),
            ],
            options={
                'verbose_name': 'Booking Agent Assignment Rule',
                'verbose_name_plural': 'Booking Agent Assignment Rules',
                'db_table': 'booking_agent_assignment_rules',
            },
        ),
        migrations.CreateModel(
            name='BookingAgentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('ESCALATION', 'Escalation'), ('FINANCE', 'Finance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_agent_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='booking_agent.bookingagentservice')),
            ],
            options={
                'verbose_name': 'Booking Agent Contact',
                'verbose_name_plural': 'Booking Agent Contacts',
                'db_table': 'booking_agent_contacts',
                'indexes': [models.Index(fields=['booking_agent_service'], name='booking_age_booking_8185e0_idx'), models.Index(fields=['email'], name='booking_age_email_0f4492_idx'), models.Index(fields=['phone'], name='booking_age_phone_5f1420_idx'), models.Index(fields=['role'], name='booking_age_role_e505fe_idx'), models.Index(fields=['is_active'], name='booking_age_is_acti_ff18cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingAgentVehicleTypeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_agent_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='booking_agent.bookingagentservice')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_agent_links', to='master_data.vehicletypemaster')),
            ],
            options={
                'verbose_name': 'Booking Agent Vehicle Type Map',
                'verbose_name_plural': 'Booking Agent Vehicle Type Maps',
                'db_table': 'booking_agent_vehicle_type_map',
                'indexes': [models.Index(fields=['booking_agent_service'], name='booking_age_booking_69d339_idx'), models.Index(fields=['vehicle_type'], name='booking_age_vehicle_368979_idx'), models.Index(fields=['is_active'], name='booking_age_is_acti_f0699d_idx')],
                'unique_together': {('booking_agent_service', 'vehicle_type')},
            },
        ),
        migrations.AddIndex(
            model_name='bookingagentservice',
            index=models.Index(fields=['booking_agent_profile'], name='booking_age_booking_94ca7f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagentservice',
            index=models.Index(fields=['profile_type'], name='booking_age_profile_ab3c00_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagentservice',
            index=models.Index(fields=['serves_all_cities'], name='booking_age_serves__c0083d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagentservice',
            index=models.Index(fields=['is_active'], name='booking_age_is_acti_2a81d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingagentservice',
            unique_together={('booking_agent_profile', 'profile_type')},
        ),
        migrations.AddIndex(
            model_name='profiletypeservicemap',
            index=models.Index(fields=['profile_type'], name='profile_typ_profile_986c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='profiletypeservicemap',
            index=models.Index(fields=['service_category'], name='profile_typ_service_b54462_idx'),
        ),
        migrations.AddIndex(
            model_name='profiletypeservicemap',
            index=models.Index(fields=['is_active'], name='profile_typ_is_acti_965bda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profiletypeservicemap',
            unique_together={('profile_type', 'service_category')},
        ),
        migrations.AddIndex(
            model_name='bookingagentservicecategory',
            index=models.Index(fields=['booking_agent_service'], name='booking_age_booking_97969f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagentservicecategory',
            index=models.Index(fields=['service_category'], name='booking_age_service_1d1ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagentservicecategory',
            index=models.Index(fields=['is_active'], name='booking_age_is_acti_38b7d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingagentservicecategory',
            unique_together={('booking_agent_service', 'service_category')},
        ),
        migrations.AddIndex(
            model_name='bookingagentassignmentrule',
            index=models.Index(fields=['service_category'], name='booking_age_service_85ae39_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagentassignmentrule',
            index=models.Index(fields=['city'], name='booking_age_city_id_1077b3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagentassignmentrule',
            index=models.Index(fields=['booking_agent_service'], name='booking_age_booking_aaa82f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagentassignmentrule',
            index=models.Index(fields=['priority'], name='booking_age_priorit_abb862_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingagentassignmentrule',
            index=models.Index(fields=['is_active'], name='booking_age_is_acti_c2ca45_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingagentassignmentrule',
            constraint=models.UniqueConstraint(fields=('service_category', 'city', 'booking_agent_service'), name='uniq_assignment_rule_service_city_agent'),
        ),
    ]
