# Generated by Django 5.2.6 on 2026-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingagentcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookingagentcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
