# Generated by Django 5.2.6 on 2025-12-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_merge_20251212_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('submit', 'Submitted'), ('cancel', 'Cancelled'), ('assign_booking', 'Booking Assigned'), ('update_booking_status', 'Booking Status Updated'), ('forward_to_travel_desk', 'Forwarded to Travel Desk'), ('ceo_resume_booking', 'CEO Resumed Booking')], max_length=30),
        ),
    ]
