# Generated by Django 5.2.6 on 2025-12-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_merge_20251212_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapplication',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_manager', 'Pending Manager Approval'), ('approved_manager', 'Approved by Manager'), ('rejected_manager', 'Rejected by Manager'), ('pending_chro', 'Pending CHRO Approval'), ('approved_chro', 'Approved by CHRO'), ('rejected_chro', 'Rejected by CHRO'), ('pending_ceo', 'Pending CEO Approval'), ('approved_ceo', 'Approved by CEO'), ('rejected_ceo', 'Rejected by CEO'), ('pending_travel_desk', 'Pending Travel Desk'), ('booking_in_progress', 'Booking in Progress'), ('booked', 'Bookings Confirmed'), ('completed', 'Travel Completed'), ('cancellation_requested', 'Cancellation Requested'), ('cancelled', 'Cancelled')], help_text='Status before cancellation was requested', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('submit', 'Submitted'), ('cancel', 'Cancelled'), ('assign_booking', 'Booking Assigned'), ('update_booking_status', 'Booking Status Updated'), ('forward_to_travel_desk', 'Forwarded to Travel Desk'), ('ceo_resume_booking', 'CEO Resumed Booking')], max_length=30),
        ),
        migrations.AlterField(
            model_name='travelapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_manager', 'Pending Manager Approval'), ('approved_manager', 'Approved by Manager'), ('rejected_manager', 'Rejected by Manager'), ('pending_chro', 'Pending CHRO Approval'), ('approved_chro', 'Approved by CHRO'), ('rejected_chro', 'Rejected by CHRO'), ('pending_ceo', 'Pending CEO Approval'), ('approved_ceo', 'Approved by CEO'), ('rejected_ceo', 'Rejected by CEO'), ('pending_travel_desk', 'Pending Travel Desk'), ('booking_in_progress', 'Booking in Progress'), ('booked', 'Bookings Confirmed'), ('completed', 'Travel Completed'), ('cancellation_requested', 'Cancellation Requested'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
