# Generated by Django 5.2.6 on 2025-12-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_travelapplication_previous_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapplication',
            name='cancellation_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting cancellation request'),
        ),
    ]
