# Generated by Django 5.2.6 on 2025-12-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_alter_auditlog_action'),
        ('travel', '0018_add_cancellation_rejection_reason'),
    ]

    operations = [
    ]
