# Generated by Django 5.2.6 on 2026-01-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_alter_grademaster_sorting_no'),
        ('travel', '0019_merge_20251229_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='no_bookings_required',
            field=models.BooleanField(default=False, help_text='If true, user explicitly stated that no bookings are required for this trip'),
        ),
        migrations.AlterField(
            model_name='travelapplication',
            name='general_ledger',
            field=models.ForeignKey(blank=True, help_text='GL code for expenses', null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.glcodemaster'),
        ),
        migrations.AlterField(
            model_name='travelapplication',
            name='internal_order',
            field=models.CharField(blank=True, help_text='IO reference number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_from', to='master_data.citymaster'),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Exact start time of travel', null=True),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_to', to='master_data.citymaster'),
        ),
    ]
