# Generated by Django 5.2.6 on 2026-01-23 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0028_alter_designationmaster_designation_name'),
        ('travel', '0020_tripdetails_no_bookings_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapplication',
            name='travel_for',
            field=models.CharField(choices=[('self', 'Self'), ('guest', 'Guest'), ('self_guest', 'Self + Guest')], default='self', help_text='Who is travelling?', max_length=20),
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality_type', models.CharField(choices=[('indian', 'Indian'), ('foreign', 'Foreign')], default='indian', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profiles', to='master_data.companyinformation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_guests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guest_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTraveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_travelers', to='travel.travelapplication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_participations', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_participations', to='travel.guestprofile')),
            ],
            options={
                'db_table': 'application_travelers',
            },
        ),
        migrations.AddIndex(
            model_name='guestprofile',
            index=models.Index(fields=['created_by'], name='guest_profi_created_8db681_idx'),
        ),
        migrations.AddIndex(
            model_name='guestprofile',
            index=models.Index(fields=['company'], name='guest_profi_company_488d76_idx'),
        ),
        migrations.AddIndex(
            model_name='guestprofile',
            index=models.Index(fields=['email'], name='guest_profi_email_92d72e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationtraveler',
            unique_together={('travel_application', 'guest'), ('travel_application', 'user')},
        ),
    ]
