# Generated by Django 5.2.6 on 2026-01-28 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0032_mealpreferencemaster'),
        ('travel', '0021_travelapplication_travel_for_guestprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtraveler',
            name='accommodation_meal_preference',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowed_modes__contains': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation_travelers', to='master_data.mealpreferencemaster'),
        ),
        migrations.AddField(
            model_name='applicationtraveler',
            name='flight_meal_preference',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowed_modes__contains': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_travelers', to='master_data.mealpreferencemaster'),
        ),
    ]
