# Generated by Django 5.2.6 on 2026-01-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_applicationtraveler_accommodation_meal_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
