# Generated by Django 5.2.6 on 2026-01-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0032_mealpreferencemaster'),
        ('travel', '0023_alter_guestprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingassignment',
            name='requested_vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Specific vehicle type requested for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.vehicletypemaster'),
        ),
    ]
