# Generated by Django 5.2.6 on 2026-01-31 10:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_bookingassignment_requested_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('processed_amount', models.DecimalField(decimal_places=2, help_text='Actual amount processed/transfered', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_mode', models.CharField(choices=[('bank_transfer', 'Bank Transfer (NEFT/RTGS/IMPS)'), ('cash', 'Cash'), ('check', 'Check/DD'), ('corporate_card', 'Corporate Card Load'), ('payroll', 'Payroll Adjustment'), ('other', 'Other')], max_length=50)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction ID, UTR, Check Number etc.', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Finance remarks')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(help_text='Link to the travel application requesting advance', on_delete=django.db.models.deletion.CASCADE, related_name='advance_processing', to='travel.travelapplication')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_advances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['status'], name='travel_adva_status_871d52_idx'), models.Index(fields=['processed_by'], name='travel_adva_process_874843_idx')],
            },
        ),
    ]
