# Generated by Django 5.2.6 on 2026-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_advanceprocessing'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapplication',
            name='bulk_upload_file',
            field=models.FileField(blank=True, help_text='Excel/CSV file for bulk booking details (Guests)', null=True, upload_to='travel/bulk_uploads/%Y/%m/'),
        ),
    ]
