# Generated by Django 5.0 on 2026-02-10 10:45

from django.db import migrations, models
import django.db.models.deletion


def populate_handling_travel_desk_user(apps, schema_editor):
    """
    Populate the new handling_travel_desk_user field with the 
    travel_desk_user from the parent TravelApplication.
    """
    Booking = apps.get_model('travel', 'Booking')
    
    # We need to traverse: Booking -> TripDetails -> TravelApplication
    # And get the travel_desk_user from there.
    # Note: This might be slow for massive datasets, but safe for normal volume.
    
    # Optimize with select_related if possible, or just iterate (safer for migrations)
    for booking in Booking.objects.all():
        try:
            # Access parent application
            application = booking.trip_details.travel_application
            if application.travel_desk_user:
                booking.handling_travel_desk_user = application.travel_desk_user
                booking.save(update_fields=['handling_travel_desk_user'])
        except Exception:
            # Handle cases where relationship might be broken (orphan bookings)
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('travel', '0026_travelapplication_bulk_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='handling_travel_desk_user',
            field=models.ForeignKey(blank=True, help_text='The specific travel desk user currently working on this booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling_bookings', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_desk_forwarded_at',
            field=models.DateTimeField(blank=True, help_text='When this booking was specifically forwarded to a desk user.', null=True),
        ),
        migrations.RunPython(populate_handling_travel_desk_user, migrations.RunPython.noop),
    ]
