# Generated by Django 5.0 on 2026-03-06

from django.db import migrations


def auto_confirm_existing_personal_vehicle_bookings(apps, schema_editor):
    """
    Find all pending bookings that use personal vehicles and mark them as confirmed.
    Also sync the application status if all bookings are confirmed.
    """
    Booking = apps.get_model('travel', 'Booking')
    TravelApplication = apps.get_model('travel', 'TravelApplication')
    
    # Names for personal car modes
    personal_modes = ['Own Car', 'Personal Car']
    
    # 1. Update pending bookings
    affected_bookings = Booking.objects.filter(
        status='pending',
        booking_type__name__in=personal_modes
    )
    
    application_ids = set()
    for booking in affected_bookings:
        booking.status = 'confirmed'
        booking.save(update_fields=['status'])
        application_ids.add(booking.trip_details.travel_application_id)
        
    # 2. Sync Application status
    # If an application has all bookings in confirmed/completed/cancelled, it should be 'booked'
    for app_id in application_ids:
        app = TravelApplication.objects.get(id=app_id)
        
        # Check for any non-terminal bookings
        has_pending = Booking.objects.filter(
            trip_details__travel_application=app,
            status__in=['pending', 'requested', 'in_progress', 'booking_in_progress']
        ).exists()
        
        if not has_pending and app.status == 'pending_travel_desk':
            app.status = 'booked'
            app.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_booking_handling_travel_desk_user'),
    ]

    operations = [
        migrations.RunPython(auto_confirm_existing_personal_vehicle_bookings, migrations.RunPython.noop),
    ]
