# Generated by Django 5.2.6 on 2026-03-26 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_auto_confirm_personal_vehicles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackdatedTRAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_from', models.DateTimeField(help_text='Start time of the permission window')),
                ('allowed_until', models.DateTimeField(help_text='End time of the permission window')),
                ('reason', models.TextField(blank=True, help_text='Administrative reason for granting this exception')),
                ('is_active', models.BooleanField(default=True, help_text='Manual override to revoke permission prematurely')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(help_text='Administrator who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_backdated_allowances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Employee who is being granted permission', on_delete=django.db.models.deletion.CASCADE, related_name='backdated_tr_allowances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Back-dated TR Allowance',
                'verbose_name_plural': 'Back-dated TR Allowances',
                'db_table': 'travel_backdated_allowance',
                'ordering': ['-created_at'],
            },
        ),
    ]
