# Generated by Django 5.2.6 on 2026-05-05 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_backdatedtrallowance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelapplication',
            name='selected_approver',
            field=models.ForeignKey(blank=True, help_text='Optional: User-selected approver. Overrides reporting_manager when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_applications_as_selected_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
