# Generated by Django 5.2.12 on 2026-05-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_add_selected_approver_to_travel_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bulk_booking_file',
            field=models.FileField(blank=True, help_text='Bulk guest data file uploaded by applicant for this booking line item (ticketing/accommodation/conveyance)', null=True, upload_to='travel/bulk_booking_files/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='travelapplication',
            name='bulk_upload_file',
            field=models.FileField(blank=True, help_text='[LEGACY] Application-level bulk booking file. Use Booking.bulk_booking_file for new records.', null=True, upload_to='travel/bulk_uploads/%Y/%m/'),
        ),
    ]
