# Generated by Django 5.2.6 on 2026-05-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0032_booking_closure'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookingclosurelog',
            new_name='travel_book_booking_fce7ed_idx',
            old_name='travel_book_booking_6a8f1d_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('in_progress', 'In Progress'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
