# Generated by Django 5.2.6 on 2026-05-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0035_ensure_travelapprovalflow_edit_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('submit', 'Submitted'), ('cancel', 'Cancelled'), ('assign_booking', 'Booking Assigned'), ('update_booking_status', 'Booking Status Updated'), ('forward_to_travel_desk', 'Forwarded to Travel Desk'), ('ceo_resume_booking', 'CEO Resumed Booking'), ('cancel_booking', 'Booking Cancelled'), ('close_booking', 'Booking Closed'), ('update_claim_elig', 'Claim Eligibility Updated')], max_length=30),
        ),
        migrations.AlterField(
            model_name='travelapplication',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Modification count (0 = original submission). Incremented on resubmit after critical edit.'),
        ),
    ]
