# Generated by Django 5.2.6 on 2026-05-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0037_travelapplicationedithistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='travelapplicationedithistory',
            new_name='travel_trav_travel__c8069c_idx',
            old_name='travel_trav_travel_a_hist_idx',
        ),
        migrations.RenameIndex(
            model_name='travelapplicationedithistory',
            new_name='travel_trav_travel__d85817_idx',
            old_name='travel_trav_travel_a_ec_idx',
        ),
    ]
